# Generated by Django 4.0.1 on 2022-01-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_title',
            field=models.CharField(default='Job', max_length=100),
        ),
    ]
